pipeline {
    agent any
   
    parameters {
        choice(choices:['plan','apply'], description: 'Request Action', name: 'CHOICE')
    }
	
	 environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
   
    stages {
        stage('checkout') {
            steps {
                git branch: 'production', credentialsId: '0734624e-5b78-43b8-bad2-874d628c10b1', url: 'https://github.com/ravikirandeekonda/bpcl-prod-tfcode.git'
            }
        }
		
        stage('Terraform init') {
            steps {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/dev'){
                sh ("terraform init")
                }
            }
        }
        
        stage('Manual Step') {
            steps('Input') {
                echo "choice: ${CHOICE}"
                echo "choice params.: " + params.CHOICE
            }
        }
        
        stage('plan') {
            when { 
                expression { params.CHOICE == 'plan' }
            }   
            
            steps('Execute Plan')    {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/dev'){
                sh ("terraform plan")
                }
            } 
        }

		stage('Terraform Apply') {
            when { 
                expression { params.CHOICE == 'apply' }
            }   
            
            steps('Execute Apply')    {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/dev'){
                sh ("terraform apply --auto-approve")
                }
            } 
        }
        
    }
}