pipeline {
    agent any

    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('checkout') {
            steps {
                git branch: 'production', credentialsId: '7306d1cf-cef9-452d-8aa5-32e7971d52a2', url: 'https://github.com/ravikirandeekonda/bpcl-prod-tfcode.git'
            }
        }
        stage('Terraform init') {
            steps {
                dir('/var/lib/jenkins/workspace/bpcl-dev-pipeline/modules/ec2'){
                sh ("terraform init")
                }
            }
        }
        stage('terraform plan') {
            steps {
                dir('/var/lib/jenkins/workspace/bpcl-dev-pipeline/modules/ec2'){
                sh ("terraform plan")
                }
            }
        }
        stage('terraform apply') {
            steps {
                dir('/var/lib/jenkins/workspace/bpcl-dev-pipeline/modules/ec2'){
                sh ("terraform apply --auto-approve")
                }
            }
        }
    }
}
