pipeline {
    agent any

    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('checkout') {
            steps {
                git branch: 'production', credentialsId: '9dc5e3e0-ef18-41bf-bc57-f5c599530be3', url: 'https://github.com/ravikirandeekonda/bpcl-prod-tfcode.git'
            }
        }
        stage('Terraform init') {
            steps {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/modules/ec2'){
                sh ("terraform init")
                }
            }
        }
        stage('terraform plan') {
            steps {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/modules/ec2'){
                sh ("terraform plan")
                }
            }
        }
        stage('terraform fmt') {
            steps {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/modules/ec2'){
                sh ("terraform fmt")
                }
            }
        }
        stage('terraform apply') {
            steps {
                dir('/var/lib/jenkins/workspace/terraform-pipeline/modules/ec2'){
                sh ("terraform apply --auto-approve")
                }
            }
        }
    }
}
